// src/utils/color-theme.ts
import { vars } from 'nativewind';

export const themes = {
  light: vars({
    '--color-primary-default': '#FDFDFD',
    '--color-primary-blue': '#347CE8',
    '--color-primary-blue2': '#1A407F',
    '--color-primary-blue2_30': '#1A407F3C',
    '--color-primary-blue2_50': '#1A407F5C',
    '--color-primary-light-blue': '#E5EFFD',
    '--color-primary-light-blue2': '#F6FBFF',
    '--color-primary-azure-blue': '#2F70E0',
    '--color-primary-azure-dark': '#3276EA',
    '--color-primary-midnight-blue': '#1C4689',
    '--color-primary-black': '#131313',
    '--color-primary-white': '#FFFFFF',
    '--color-primary-100': '#414A5B',
    '--color-primary-cool-gray': '#838B9D',
    '--color-primary-steel-gray': '#A4A4A7',
    '--color-primary-pale-gray': '#F2F2F2',
    '--color-secondary-gray': '#353535',
    '--color-secondary-light-gray': '#A0A0A0',
    '--color-secondary-light-gray2': '#EAEAEA',
    '--color-secondary-gray3': '#EAEAEA',
    '--color-secondary-cloud-gray': '#DDDDDD',
    '--color-secondary-ash-gray': '#6F6F6F',
    '--color-secondary-red': '#D70000',
    '--color-secondary-green': '#3DD26A',
    '--color-secondary-sunset-yellow': '#FFBD3C',
    '--color-secondary-sky-blue': '#3CADFF',
    '--color-secondary-violet': '#A93CFF',
    '--color-secondary-light-green': '#EDF6F2',
    '--color-secondary-sky-mist': '#E6EBF4',
    '--color-secondary-disable': '#F7F7F7',
    '--color-secondary-warning': '#FFEBDB',
    '--color-secondary-success': '#FF7F1F',
    '--color-secondary-error': '#FFD7D7',
    '--color-gradient': 'linear-gradient(180deg, #3275E9 0%, #1B4181 100%)',
  }),
  dark: vars({
    '--color-primary-default': '#FDFDFD',
    '--color-primary-blue': '#347CE8',
    '--color-primary-blue2': '#1A407F',
    '--color-primary-light-blue': '#E5EFFD',
    '--color-primary-light-blue2': '#F6FBFF',
    '--color-primary-azure-blue': '#2F70E0',
    '--color-primary-azure-dark': '#3276EA',
    '--color-primary-midnight-blue': '#1C4689',
    '--color-primary-black': '#131313',
    '--color-primary-white': '#FFFFFF',
    '--color-secondary-gray': '#353535',
    '--color-secondary-light-gray': '#A0A0A0',
    '--color-secondary-light-gray2': '#EAEAEA',
    '--color-secondary-gray3': '#EAEAEA',
    '--color-secondary-red': '#D70000',
    '--color-secondary-green': '#3DD26A',
    '--color-secondary-light-green': '#EDF6F2',
    '--color-secondary-sky-mist': '#E6EBF4',
    '--color-secondary-disable': '#F7F7F7',
    '--color-primary-100': '#414A5B',
    '--color-gradient': 'linear-gradient(180deg, #3275E9 0%, #1B4181 100%)',
  }),
};
